# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
os:
  - linux

r: bioc-release

repos:
  CRAN: https://cran.r-project.org/

addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin # libnetcdf-dev doesn't contain nc-config in ubuntu 12.04 (in 16.04 it is part of libnetcdf-dev)
      - libhdf5-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

